services:
  - type: web
    name: Space-Xmd
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node index.js"
    services:
  - type: web
    plan: free
    name: django-app
    runtime: python
    repo: https://github.com/render/django.git
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-app-db
          property: connectionString

databases:
  - name: django-app-db
    plan: free
